name: run py checkin

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: 9 14 * * *

jobs:
  runpy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: python checkin.py
        env:
          GLADOS: ${{ secrets.GLADOS }}
          NOTIFY: ${{ secrets.NOTIFY }}
